endpoints:
  - name: mfa
    url: https://mfa.workbench.web.id/up
    interval: 60s
    conditions:
      - "[STATUS] <= 299"
      - "[BODY] == pat(*2FAuth up*)"
    alerts:
      - type: ntfy
  
  - name: trxcker
    url: https://trxcker.workbench.web.id
    interval: 60s
    conditions:
      - "[STATUS] <= 299"
    alerts:
      - type: ntfy
  
  - name: postgres
    url: tcp://postgres:5432
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: ntfy

  - name: prometheus
    url: http://prometheus:9090/-/healthy
    interval: 60s
    conditions:
      - "[STATUS] <= 299"
    alerts:
      - type: ntfy

  - name: traefik
    url: http://traefik:80/ping
    interval: 60s
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: ntfy